version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  gosell-net:
    build:
      context: .
      dockerfile: Development.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis